// Autogenerated from Pigeon (v2.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by FLTHostScreenBrightnessApi.
NSObject<FlutterMessageCodec> *FLTHostScreenBrightnessApiGetCodec(void);

@protocol FLTHostScreenBrightnessApi
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getSystemBrightnessWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getCurrentBrightnessWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)setScreenBrightnessBrightness:(NSNumber *)brightness error:(FlutterError *_Nullable *_Nonnull)error;
- (void)resetScreenBrightnessWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)hasChangedWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTHostScreenBrightnessApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTHostScreenBrightnessApi> *_Nullable api);

NS_ASSUME_NONNULL_END
