// Autogenerated from Pigeon (v2.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "messages.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}


@interface FLTFeedbackTypeClass ()
+ (FLTFeedbackTypeClass *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation FLTFeedbackTypeClass
+ (instancetype)makeWithType:(FLTFeedbackType)type {
  FLTFeedbackTypeClass* pigeonResult = [[FLTFeedbackTypeClass alloc] init];
  pigeonResult.type = type;
  return pigeonResult;
}
+ (FLTFeedbackTypeClass *)fromMap:(NSDictionary *)dict {
  FLTFeedbackTypeClass *pigeonResult = [[FLTFeedbackTypeClass alloc] init];
  pigeonResult.type = [GetNullableObject(dict, @"type") integerValue];
  return pigeonResult;
}
- (NSDictionary *)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:@(self.type), @"type", nil];
}
@end

@interface FLTHostVibratePluginApiCodecReader : FlutterStandardReader
@end
@implementation FLTHostVibratePluginApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [FLTFeedbackTypeClass fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface FLTHostVibratePluginApiCodecWriter : FlutterStandardWriter
@end
@implementation FLTHostVibratePluginApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[FLTFeedbackTypeClass class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface FLTHostVibratePluginApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FLTHostVibratePluginApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FLTHostVibratePluginApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FLTHostVibratePluginApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FLTHostVibratePluginApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    FLTHostVibratePluginApiCodecReaderWriter *readerWriter = [[FLTHostVibratePluginApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void FLTHostVibratePluginApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTHostVibratePluginApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.HostVibratePluginApi.vibrate"
        binaryMessenger:binaryMessenger
        codec:FLTHostVibratePluginApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(vibrateDuration:error:)], @"FLTHostVibratePluginApi api (%@) doesn't respond to @selector(vibrateDuration:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSNumber *arg_duration = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api vibrateDuration:arg_duration error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.HostVibratePluginApi.canVibrate"
        binaryMessenger:binaryMessenger
        codec:FLTHostVibratePluginApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(canVibrateWithError:)], @"FLTHostVibratePluginApi api (%@) doesn't respond to @selector(canVibrateWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api canVibrateWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.HostVibratePluginApi.feedback"
        binaryMessenger:binaryMessenger
        codec:FLTHostVibratePluginApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(feedbackFeedbackType:error:)], @"FLTHostVibratePluginApi api (%@) doesn't respond to @selector(feedbackFeedbackType:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        FLTFeedbackTypeClass *arg_feedbackType = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api feedbackFeedbackType:arg_feedbackType error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
