// Autogenerated from Pigeon (v2.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, FLTFeedbackType) {
  FLTFeedbackTypeSuccess = 0,
  FLTFeedbackTypeError = 1,
  FLTFeedbackTypeWarning = 2,
  FLTFeedbackTypeSelection = 3,
  FLTFeedbackTypeImpact = 4,
  FLTFeedbackTypeHeavy = 5,
  FLTFeedbackTypeMedium = 6,
  FLTFeedbackTypeLight = 7,
};

@class FLTFeedbackTypeClass;

@interface FLTFeedbackTypeClass : NSObject
+ (instancetype)makeWithType:(FLTFeedbackType)type;
@property(nonatomic, assign) FLTFeedbackType type;
@end

/// The codec used by FLTHostVibratePluginApi.
NSObject<FlutterMessageCodec> *FLTHostVibratePluginApiGetCodec(void);

@protocol FLTHostVibratePluginApi
- (void)vibrateDuration:(NSNumber *)duration error:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)canVibrateWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)feedbackFeedbackType:(FLTFeedbackTypeClass *)feedbackType error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTHostVibratePluginApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTHostVibratePluginApi> *_Nullable api);

NS_ASSUME_NONNULL_END
