name: getx
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1 # getX框架

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4