final countries = 
[
  {
    "en":"Angola",
    "zh":"安哥拉",
    "tr":"安哥拉",
    "locale":"AO",
    "code":244
  },
  {
    "en":"Afghanistan",
    "zh":"阿富汗",
    "tr":"阿富汗",
    "locale":"AF",
    "code":93
  },
  {
    "en":"Albania",
    "zh":"阿尔巴尼亚",
    "tr":"阿爾巴尼亞",
    "locale":"AL",
    "code":355
  },
  {
    "en":"Algeria",
    "zh":"阿尔及利亚",
    "tr":"阿爾及利亞",
    "locale":"DZ",
    "code":213
  },
  {
    "en":"Andorra",
    "zh":"安道尔共和国",
    "tr":"安道爾共和國",
    "locale":"AD",
    "code":376
  },
  {
    "en":"Anguilla",
    "zh":"安圭拉岛",
    "tr":"安圭拉島",
    "locale":"AI",
    "code":1264
  },
  {
    "en":"Antigua and Barbuda",
    "zh":"安提瓜和巴布达",
    "tr":"安提瓜和巴布達",
    "locale":"AG",
    "code":1268
  },
  {
    "en":"Argentina",
    "zh":"阿根廷",
    "tr":"阿根廷",
    "locale":"AR",
    "code":54
  },
  {
    "en":"Armenia",
    "zh":"亚美尼亚",
    "tr":"亞美尼亞",
    "locale":"AM",
    "code":374
  },
  {
    "en":"Ascension",
    "zh":"阿森松",
    "tr":"阿森鬆",
    "locale":" ",
    "code":247
  },
  {
    "en":"Australia",
    "zh":"澳大利亚",
    "tr":"澳大利亞",
    "locale":"AU",
    "code":61
  },
  {
    "en":"Austria",
    "zh":"奥地利",
    "tr":"奧地利",
    "locale":"AT",
    "code":43
  },
  {
    "en":"Azerbaijan",
    "zh":"阿塞拜疆",
    "tr":"阿塞拜疆",
    "locale":"AZ",
    "code":994
  },
  {
    "en":"Bahamas",
    "zh":"巴哈马",
    "tr":"巴哈馬",
    "locale":"BS",
    "code":1242
  },
  {
    "en":"Bahrain",
    "zh":"巴林",
    "tr":"巴林",
    "locale":"BH",
    "code":973
  },
  {
    "en":"Bangladesh",
    "zh":"孟加拉国",
    "tr":"孟加拉國",
    "locale":"BD",
    "code":880
  },
  {
    "en":"Barbados",
    "zh":"巴巴多斯",
    "tr":"巴巴多斯",
    "locale":"BB",
    "code":1246
  },
  {
    "en":"Belarus",
    "zh":"白俄罗斯",
    "tr":"白俄羅斯",
    "locale":"BY",
    "code":375
  },
  {
    "en":"Belgium",
    "zh":"比利时",
    "tr":"比利時",
    "locale":"BE",
    "code":32
  },
  {
    "en":"Belize",
    "zh":"伯利兹",
    "tr":"伯利茲",
    "locale":"BZ",
    "code":501
  },
  {
    "en":"Benin",
    "zh":"贝宁",
    "tr":"貝寧",
    "locale":"BJ",
    "code":229
  },
  {
    "en":"Bermuda Is.",
    "zh":"百慕大群岛",
    "tr":"百慕大群島",
    "locale":"BM",
    "code":1441
  },
  {
    "en":"Bolivia",
    "zh":"玻利维亚",
    "tr":"玻利維亞",
    "locale":"BO",
    "code":591
  },
  {
    "en":"Botswana",
    "zh":"博茨瓦纳",
    "tr":"博茨瓦納",
    "locale":"BW",
    "code":267
  },
  {
    "en":"Brazil",
    "zh":"巴西",
    "tr":"巴西",
    "locale":"BR",
    "code":55
  },
  {
    "en":"Brunei",
    "zh":"文莱",
    "tr":"文萊",
    "locale":"BN",
    "code":673
  },
  {
    "en":"Bulgaria",
    "zh":"保加利亚",
    "tr":"保加利亞",
    "locale":"BG",
    "code":359
  },
  {
    "en":"Burkina-faso",
    "zh":"布基纳法索",
    "tr":"布基納法索",
    "locale":"BF",
    "code":226
  },
  {
    "en":"Burma",
    "zh":"缅甸",
    "tr":"緬甸",
    "locale":"MM",
    "code":95
  },
  {
    "en":"Burundi",
    "zh":"布隆迪",
    "tr":"布隆迪",
    "locale":"BI",
    "code":257
  },
  {
    "en":"Cameroon",
    "zh":"喀麦隆",
    "tr":"喀麥隆",
    "locale":"CM",
    "code":237
  },
  {
    "en":"Canada",
    "zh":"加拿大",
    "tr":"加拿大",
    "locale":"CA",
    "code":1
  },
  {
    "en":"Cayman Is.",
    "zh":"开曼群岛",
    "tr":"開曼群島",
    "locale":" ",
    "code":1345
  },
  {
    "en":"Central African Republic",
    "zh":"中非共和国",
    "tr":"中非共和國",
    "locale":"CF",
    "code":236
  },
  {
    "en":"Chad",
    "zh":"乍得",
    "tr":"乍得",
    "locale":"TD",
    "code":235
  },
  {
    "en":"Chile",
    "zh":"智利",
    "tr":"智利",
    "locale":"CL",
    "code":56
  },
  {
    "en":"China",
    "zh":"中国",
    "tr":"中國",
    "locale":"CN",
    "code":86
  },
  {
    "en":"Colombia",
    "zh":"哥伦比亚",
    "tr":"哥倫比亞",
    "locale":"CO",
    "code":57
  },
  {
    "en":"Congo",
    "zh":"刚果",
    "tr":"剛果",
    "locale":"CG",
    "code":242
  },
  {
    "en":"Cook Is.",
    "zh":"库克群岛",
    "tr":"庫克群島",
    "locale":"CK",
    "code":682
  },
  {
    "en":"Costa Rica",
    "zh":"哥斯达黎加",
    "tr":"哥斯達黎加",
    "locale":"CR",
    "code":506
  },
  {
    "en":"Cuba",
    "zh":"古巴",
    "tr":"古巴",
    "locale":"CU",
    "code":53
  },
  {
    "en":"Cyprus",
    "zh":"塞浦路斯",
    "tr":"塞浦路斯",
    "locale":"CY",
    "code":357
  },
  {
    "en":"Czech Republic",
    "zh":"捷克",
    "tr":"捷克",
    "locale":"CZ",
    "code":420
  },
  {
    "en":"Denmark",
    "zh":"丹麦",
    "tr":"丹麥",
    "locale":"DK",
    "code":45
  },
  {
    "en":"Djibouti",
    "zh":"吉布提",
    "tr":"吉布提",
    "locale":"DJ",
    "code":253
  },
  {
    "en":"Dominica Rep.",
    "zh":"多米尼加共和国",
    "tr":"多米尼加共和國",
    "locale":"DO",
    "code":1890
  },
  {
    "en":"Ecuador",
    "zh":"厄瓜多尔",
    "tr":"厄瓜多爾",
    "locale":"EC",
    "code":593
  },
  {
    "en":"Egypt",
    "zh":"埃及",
    "tr":"埃及",
    "locale":"EG",
    "code":20
  },
  {
    "en":"EI Salvador",
    "zh":"萨尔瓦多",
    "tr":"薩爾瓦多",
    "locale":"SV",
    "code":503
  },
  {
    "en":"Estonia",
    "zh":"爱沙尼亚",
    "tr":"愛沙尼亞",
    "locale":"EE",
    "code":372
  },
  {
    "en":"Ethiopia",
    "zh":"埃塞俄比亚",
    "tr":"埃塞俄比亞",
    "locale":"ET",
    "code":251
  },
  {
    "en":"Fiji",
    "zh":"斐济",
    "tr":"斐濟",
    "locale":"FJ",
    "code":679
  },
  {
    "en":"Finland",
    "zh":"芬兰",
    "tr":"芬蘭",
    "locale":"FI",
    "code":358
  },
  {
    "en":"France",
    "zh":"法国",
    "tr":"法國",
    "locale":"FR",
    "code":33
  },
  {
    "en":"French Guiana",
    "zh":"法属圭亚那",
    "tr":"法屬圭亞那",
    "locale":"GF",
    "code":594
  },
  {
    "en":"Gabon",
    "zh":"加蓬",
    "tr":"加蓬",
    "locale":"GA",
    "code":241
  },
  {
    "en":"Gambia",
    "zh":"冈比亚",
    "tr":"岡比亞",
    "locale":"GM",
    "code":220
  },
  {
    "en":"Georgia",
    "zh":"格鲁吉亚",
    "tr":"格魯吉亞",
    "locale":"GE",
    "code":995
  },
  {
    "en":"Germany",
    "zh":"德国",
    "tr":"德國",
    "locale":"DE",
    "code":49
  },
  {
    "en":"Ghana",
    "zh":"加纳",
    "tr":"加納",
    "locale":"GH",
    "code":233
  },
  {
    "en":"Gibraltar",
    "zh":"直布罗陀",
    "tr":"直布羅陀",
    "locale":"GI",
    "code":350
  },
  {
    "en":"Greece",
    "zh":"希腊",
    "tr":"希臘",
    "locale":"GR",
    "code":30
  },
  {
    "en":"Grenada",
    "zh":"格林纳达",
    "tr":"格林納達",
    "locale":"GD",
    "code":1809
  },
  {
    "en":"Guam",
    "zh":"关岛",
    "tr":"關島",
    "locale":"GU",
    "code":1671
  },
  {
    "en":"Guatemala",
    "zh":"危地马拉",
    "tr":"危地馬拉",
    "locale":"GT",
    "code":502
  },
  {
    "en":"Guinea",
    "zh":"几内亚",
    "tr":"幾內亞",
    "locale":"GN",
    "code":224
  },
  {
    "en":"Guyana",
    "zh":"圭亚那",
    "tr":"圭亞那",
    "locale":"GY",
    "code":592
  },
  {
    "en":"Haiti",
    "zh":"海地",
    "tr":"海地",
    "locale":"HT",
    "code":509
  },
  {
    "en":"Honduras",
    "zh":"洪都拉斯",
    "tr":"洪都拉斯",
    "locale":"HN",
    "code":504
  },
  {
    "en":"Hongkong",
    "zh":"香港",
    "tr":"香港",
    "locale":"HK",
    "code":852
  },
  {
    "en":"Hungary",
    "zh":"匈牙利",
    "tr":"匈牙利",
    "locale":"HU",
    "code":36
  },
  {
    "en":"Iceland",
    "zh":"冰岛",
    "tr":"冰島",
    "locale":"IS",
    "code":354
  },
  {
    "en":"India",
    "zh":"印度",
    "tr":"印度",
    "locale":"IN",
    "code":91
  },
  {
    "en":"Indonesia",
    "zh":"印度尼西亚",
    "tr":"印度尼西亞",
    "locale":"ID",
    "code":62
  },
  {
    "en":"Iran",
    "zh":"伊朗",
    "tr":"伊朗",
    "locale":"IR",
    "code":98
  },
  {
    "en":"Iraq",
    "zh":"伊拉克",
    "tr":"伊拉克",
    "locale":"IQ",
    "code":964
  },
  {
    "en":"Ireland",
    "zh":"爱尔兰",
    "tr":"愛爾蘭",
    "locale":"IE",
    "code":353
  },
  {
    "en":"Israel",
    "zh":"以色列",
    "tr":"以色列",
    "locale":"IL",
    "code":972
  },
  {
    "en":"Italy",
    "zh":"意大利",
    "tr":"意大利",
    "locale":"IT",
    "code":39
  },
  {
    "en":"Ivory Coast",
    "zh":"科特迪瓦",
    "tr":"科特迪瓦",
    "locale":" ",
    "code":225
  },
  {
    "en":"Jamaica",
    "zh":"牙买加",
    "tr":"牙買加",
    "locale":"JM",
    "code":1876
  },
  {
    "en":"Japan",
    "zh":"日本",
    "tr":"日本",
    "locale":"JP",
    "code":81
  },
  {
    "en":"Jordan",
    "zh":"约旦",
    "tr":"約旦",
    "locale":"JO",
    "code":962
  },
  {
    "en":"Kampuchea (Cambodia )",
    "zh":"柬埔寨",
    "tr":"柬埔寨",
    "locale":"KH",
    "code":855
  },
  {
    "en":"Kazakstan",
    "zh":"哈萨克斯坦",
    "tr":"哈薩克斯坦",
    "locale":"KZ",
    "code":327
  },
  {
    "en":"Kenya",
    "zh":"肯尼亚",
    "tr":"肯尼亞",
    "locale":"KE",
    "code":254
  },
  {
    "en":"Korea",
    "zh":"韩国",
    "tr":"韓國",
    "locale":"KR",
    "code":82
  },
  {
    "en":"Kuwait",
    "zh":"科威特",
    "tr":"科威特",
    "locale":"KW",
    "code":965
  },
  {
    "en":"Kyrgyzstan",
    "zh":"吉尔吉斯坦",
    "tr":"吉爾吉斯坦",
    "locale":"KG",
    "code":331
  },
  {
    "en":"Laos",
    "zh":"老挝",
    "tr":"老撾",
    "locale":"LA",
    "code":856
  },
  {
    "en":"Latvia",
    "zh":"拉脱维亚",
    "tr":"拉脫維亞",
    "locale":"LV",
    "code":371
  },
  {
    "en":"Lebanon",
    "zh":"黎巴嫩",
    "tr":"黎巴嫩",
    "locale":"LB",
    "code":961
  },
  {
    "en":"Lesotho",
    "zh":"莱索托",
    "tr":"萊索托",
    "locale":"LS",
    "code":266
  },
  {
    "en":"Liberia",
    "zh":"利比里亚",
    "tr":"利比裡亞",
    "locale":"LR",
    "code":231
  },
  {
    "en":"Libya",
    "zh":"利比亚",
    "tr":"利比亞",
    "locale":"LY",
    "code":218
  },
  {
    "en":"Liechtenstein",
    "zh":"列支敦士登",
    "tr":"列支敦士登",
    "locale":"LI",
    "code":423
  },
  {
    "en":"Lithuania",
    "zh":"立陶宛",
    "tr":"立陶宛",
    "locale":"LT",
    "code":370
  },
  {
    "en":"Luxembourg",
    "zh":"卢森堡",
    "tr":"盧森堡",
    "locale":"LU",
    "code":352
  },
  {
    "en":"Macao",
    "zh":"澳门",
    "tr":"澳門",
    "locale":"MO",
    "code":853
  },
  {
    "en":"Madagascar",
    "zh":"马达加斯加",
    "tr":"馬達加斯加",
    "locale":"MG",
    "code":261
  },
  {
    "en":"Malawi",
    "zh":"马拉维",
    "tr":"馬拉維",
    "locale":"MW",
    "code":265
  },
  {
    "en":"Malaysia",
    "zh":"马来西亚",
    "tr":"馬來西亞",
    "locale":"MY",
    "code":60
  },
  {
    "en":"Maldives",
    "zh":"马尔代夫",
    "tr":"馬爾代夫",
    "locale":"MV",
    "code":960
  },
  {
    "en":"Mali",
    "zh":"马里",
    "tr":"馬裡",
    "locale":"ML",
    "code":223
  },
  {
    "en":"Malta",
    "zh":"马耳他",
    "tr":"馬耳他",
    "locale":"MT",
    "code":356
  },
  {
    "en":"Mariana Is",
    "zh":"马里亚那群岛",
    "tr":"馬裡亞那群島",
    "locale":" ",
    "code":1670
  },
  {
    "en":"Martinique",
    "zh":"马提尼克",
    "tr":"馬提尼克",
    "locale":" ",
    "code":596
  },
  {
    "en":"Mauritius",
    "zh":"毛里求斯",
    "tr":"毛裡求斯",
    "locale":"MU",
    "code":230
  },
  {
    "en":"Mexico",
    "zh":"墨西哥",
    "tr":"墨西哥",
    "locale":"MX",
    "code":52
  },
  {
    "en":"Moldova, Republic of",
    "zh":"摩尔多瓦",
    "tr":"摩爾多瓦",
    "locale":"MD",
    "code":373
  },
  {
    "en":"Monaco",
    "zh":"摩纳哥",
    "tr":"摩納哥",
    "locale":"MC",
    "code":377
  },
  {
    "en":"Mongolia",
    "zh":"蒙古",
    "tr":"蒙古",
    "locale":"MN",
    "code":976
  },
  {
    "en":"Montserrat Is",
    "zh":"蒙特塞拉特岛",
    "tr":"蒙特塞拉特島",
    "locale":"MS",
    "code":1664
  },
  {
    "en":"Morocco",
    "zh":"摩洛哥",
    "tr":"摩洛哥",
    "locale":"MA",
    "code":212
  },
  {
    "en":"Mozambique",
    "zh":"莫桑比克",
    "tr":"莫桑比克",
    "locale":"MZ",
    "code":258
  },
  {
    "en":"Namibia",
    "zh":"纳米比亚",
    "tr":"納米比亞",
    "locale":"NA",
    "code":264
  },
  {
    "en":"Nauru",
    "zh":"瑙鲁",
    "tr":"瑙魯",
    "locale":"NR",
    "code":674
  },
  {
    "en":"Nepal",
    "zh":"尼泊尔",
    "tr":"尼泊爾",
    "locale":"NP",
    "code":977
  },
  {
    "en":"Netheriands Antilles",
    "zh":"荷属安的列斯",
    "tr":"荷屬安的列斯",
    "locale":" ",
    "code":599
  },
  {
    "en":"Netherlands",
    "zh":"荷兰",
    "tr":"荷蘭",
    "locale":"NL",
    "code":31
  },
  {
    "en":"New Zealand",
    "zh":"新西兰",
    "tr":"新西蘭",
    "locale":"NZ",
    "code":64
  },
  {
    "en":"Nicaragua",
    "zh":"尼加拉瓜",
    "tr":"尼加拉瓜",
    "locale":"NI",
    "code":505
  },
  {
    "en":"Niger",
    "zh":"尼日尔",
    "tr":"尼日爾",
    "locale":"NE",
    "code":227
  },
  {
    "en":"Nigeria",
    "zh":"尼日利亚",
    "tr":"尼日利亞",
    "locale":"NG",
    "code":234
  },
  {
    "en":"North Korea",
    "zh":"朝鲜",
    "tr":"朝鮮",
    "locale":"KP",
    "code":850
  },
  {
    "en":"Norway",
    "zh":"挪威",
    "tr":"挪威",
    "locale":"NO",
    "code":47
  },
  {
    "en":"Oman",
    "zh":"阿曼",
    "tr":"阿曼",
    "locale":"OM",
    "code":968
  },
  {
    "en":"Pakistan",
    "zh":"巴基斯坦",
    "tr":"巴基斯坦",
    "locale":"PK",
    "code":92
  },
  {
    "en":"Panama",
    "zh":"巴拿马",
    "tr":"巴拿馬",
    "locale":"PA",
    "code":507
  },
  {
    "en":"Papua New Cuinea",
    "zh":"巴布亚新几内亚",
    "tr":"巴布亞新幾內亞",
    "locale":"PG",
    "code":675
  },
  {
    "en":"Paraguay",
    "zh":"巴拉圭",
    "tr":"巴拉圭",
    "locale":"PY",
    "code":595
  },
  {
    "en":"Peru",
    "zh":"秘鲁",
    "tr":"秘魯",
    "locale":"PE",
    "code":51
  },
  {
    "en":"Philippines",
    "zh":"菲律宾",
    "tr":"菲律賓",
    "locale":"PH",
    "code":63
  },
  {
    "en":"Poland",
    "zh":"波兰",
    "tr":"波蘭",
    "locale":"PL",
    "code":48
  },
  {
    "en":"French Polynesia",
    "zh":"法属玻利尼西亚",
    "tr":"法屬玻利尼西亞",
    "locale":"PF",
    "code":689
  },
  {
    "en":"Portugal",
    "zh":"葡萄牙",
    "tr":"葡萄牙",
    "locale":"PT",
    "code":351
  },
  {
    "en":"Puerto Rico",
    "zh":"波多黎各",
    "tr":"波多黎各",
    "locale":"PR",
    "code":1787
  },
  {
    "en":"Qatar",
    "zh":"卡塔尔",
    "tr":"卡塔爾",
    "locale":"QA",
    "code":974
  },
  {
    "en":"Reunion",
    "zh":"留尼旺",
    "tr":"留尼旺",
    "locale":" ",
    "code":262
  },
  {
    "en":"Romania",
    "zh":"罗马尼亚",
    "tr":"羅馬尼亞",
    "locale":"RO",
    "code":40
  },
  {
    "en":"Russia",
    "zh":"俄罗斯",
    "tr":"俄羅斯",
    "locale":"RU",
    "code":7
  },
  {
    "en":"Saint Lueia",
    "zh":"圣卢西亚",
    "tr":"聖盧西亞",
    "locale":"LC",
    "code":1758
  },
  {
    "en":"Saint Vincent",
    "zh":"圣文森特岛",
    "tr":"聖文森特島",
    "locale":"VC",
    "code":1784
  },
  {
    "en":"Samoa Eastern",
    "zh":"东萨摩亚(美)",
    "tr":"東薩摩亞(美)",
    "locale":" ",
    "code":684
  },
  {
    "en":"Samoa Western",
    "zh":"西萨摩亚",
    "tr":"西薩摩亞",
    "locale":" ",
    "code":685
  },
  {
    "en":"San Marino",
    "zh":"圣马力诺",
    "tr":"聖馬力諾",
    "locale":"SM",
    "code":378
  },
  {
    "en":"Sao Tome and Principe",
    "zh":"圣多美和普林西比",
    "tr":"聖多美和普林西比",
    "locale":"ST",
    "code":239
  },
  {
    "en":"Saudi Arabia",
    "zh":"沙特阿拉伯",
    "tr":"沙特阿拉伯",
    "locale":"SA",
    "code":966
  },
  {
    "en":"Senegal",
    "zh":"塞内加尔",
    "tr":"塞內加爾",
    "locale":"SN",
    "code":221
  },
  {
    "en":"Seychelles",
    "zh":"塞舌尔",
    "tr":"塞舌爾",
    "locale":"SC",
    "code":248
  },
  {
    "en":"Sierra Leone",
    "zh":"塞拉利昂",
    "tr":"塞拉利昂",
    "locale":"SL",
    "code":232
  },
  {
    "en":"Singapore",
    "zh":"新加坡",
    "tr":"新加坡",
    "locale":"SG",
    "code":65
  },
  {
    "en":"Slovakia",
    "zh":"斯洛伐克",
    "tr":"斯洛伐克",
    "locale":"SK",
    "code":421
  },
  {
    "en":"Slovenia",
    "zh":"斯洛文尼亚",
    "tr":"斯洛文尼亞",
    "locale":"SI",
    "code":386
  },
  {
    "en":"Solomon Is",
    "zh":"所罗门群岛",
    "tr":"所羅門群島",
    "locale":"SB",
    "code":677
  },
  {
    "en":"Somali",
    "zh":"索马里",
    "tr":"索馬裡",
    "locale":"SO",
    "code":252
  },
  {
    "en":"South Africa",
    "zh":"南非",
    "tr":"南非",
    "locale":"ZA",
    "code":27
  },
  {
    "en":"Spain",
    "zh":"西班牙",
    "tr":"西班牙",
    "locale":"ES",
    "code":34
  },
  {
    "en":"Sri Lanka",
    "zh":"斯里兰卡",
    "tr":"斯裡蘭卡",
    "locale":"LK",
    "code":94
  },
  {
    "en":"St.Lucia",
    "zh":"圣卢西亚",
    "tr":"聖盧西亞",
    "locale":"LC",
    "code":1758
  },
  {
    "en":"St.Vincent",
    "zh":"圣文森特",
    "tr":"聖文森特",
    "locale":"VC",
    "code":1784
  },
  {
    "en":"Sudan",
    "zh":"苏丹",
    "tr":"蘇丹",
    "locale":"SD",
    "code":249
  },
  {
    "en":"Suriname",
    "zh":"苏里南",
    "tr":"蘇裡南",
    "locale":"SR",
    "code":597
  },
  {
    "en":"Swaziland",
    "zh":"斯威士兰",
    "tr":"斯威士蘭",
    "locale":"SZ",
    "code":268
  },
  {
    "en":"Sweden",
    "zh":"瑞典",
    "tr":"瑞典",
    "locale":"SE",
    "code":46
  },
  {
    "en":"Switzerland",
    "zh":"瑞士",
    "tr":"瑞士",
    "locale":"CH",
    "code":41
  },
  {
    "en":"Syria",
    "zh":"叙利亚",
    "tr":"敘利亞",
    "locale":"SY",
    "code":963
  },
  {
    "en":"Taiwan",
    "zh":"台湾省",
    "tr":"臺灣省",
    "locale":"TW",
    "code":886
  },
  {
    "en":"Tajikstan",
    "zh":"塔吉克斯坦",
    "tr":"塔吉克斯坦",
    "locale":"TJ",
    "code":992
  },
  {
    "en":"Tanzania",
    "zh":"坦桑尼亚",
    "tr":"坦桑尼亞",
    "locale":"TZ",
    "code":255
  },
  {
    "en":"Thailand",
    "zh":"泰国",
    "tr":"泰國",
    "locale":"TH",
    "code":66
  },
  {
    "en":"Togo",
    "zh":"多哥",
    "tr":"多哥",
    "locale":"TG",
    "code":228
  },
  {
    "en":"Tonga",
    "zh":"汤加",
    "tr":"湯加",
    "locale":"TO",
    "code":676
  },
  {
    "en":"Trinidad and Tobago",
    "zh":"特立尼达和多巴哥",
    "tr":"特立尼達和多巴哥",
    "locale":"TT",
    "code":1809
  },
  {
    "en":"Tunisia",
    "zh":"突尼斯",
    "tr":"突尼斯",
    "locale":"TN",
    "code":216
  },
  {
    "en":"Turkey",
    "zh":"土耳其",
    "tr":"土耳其",
    "locale":"TR",
    "code":90
  },
  {
    "en":"Turkmenistan",
    "zh":"土库曼斯坦",
    "tr":"土庫曼斯坦",
    "locale":"TM",
    "code":993
  },
  {
    "en":"Uganda",
    "zh":"乌干达",
    "tr":"烏干達",
    "locale":"UG",
    "code":256
  },
  {
    "en":"Ukraine",
    "zh":"乌克兰",
    "tr":"烏克蘭",
    "locale":"UA",
    "code":380
  },
  {
    "en":"United Arab Emirates",
    "zh":"阿拉伯联合酋长国",
    "tr":"阿拉伯聯合酋長國",
    "locale":"AE",
    "code":971
  },
  {
    "en":"United Kiongdom",
    "zh":"英国",
    "tr":"英國",
    "locale":"GB",
    "code":44
  },
  {
    "en":"United States of America",
    "zh":"美国",
    "tr":"美國",
    "locale":"US",
    "code":1
  },
  {
    "en":"Uruguay",
    "zh":"乌拉圭",
    "tr":"烏拉圭",
    "locale":"UY",
    "code":598
  },
  {
    "en":"Uzbekistan",
    "zh":"乌兹别克斯坦",
    "tr":"烏茲彆克斯坦",
    "locale":"UZ",
    "code":233
  },
  {
    "en":"Venezuela",
    "zh":"委内瑞拉",
    "tr":"委內瑞拉",
    "locale":"VE",
    "code":58
  },
  {
    "en":"Vietnam",
    "zh":"越南",
    "tr":"越南",
    "locale":"VN",
    "code":84
  },
  {
    "en":"Yemen",
    "zh":"也门",
    "tr":"也門",
    "locale":"YE",
    "code":967
  },
  {
    "en":"Yugoslavia",
    "zh":"南斯拉夫",
    "tr":"南斯拉夫",
    "locale":"YU",
    "code":381
  },
  {
    "en":"Zimbabwe",
    "zh":"津巴布韦",
    "tr":"津巴布韋",
    "locale":"ZW",
    "code":263
  },
  {
    "en":"Zaire",
    "zh":"扎伊尔",
    "tr":"紮伊爾",
    "locale":"ZR",
    "code":243
  },
  {
    "en":"Zambia",
    "zh":"赞比亚",
    "tr":"讚比亞",
    "locale":"ZM",
    "code":260
  }
];
