name: flukit
version: 1.0.3
publish_to: none

environment:
  sdk:  ">=2.14.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_cache_manager: ^3.3.0
  common:
    path: ../common

dev_dependencies:
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
