name: my_sentry
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sentry_flutter: ^6.3.0 # 日志、崩溃收集工具
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4