name: moor_db
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.4
  sqflite: ^2.0.2

dev_dependencies:
  drift_dev: ^1.5.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  flutter_lints: ^1.0.4