name: dio_http
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.4
  cookie_jar: ^3.0.1
  dio_cache_interceptor: ^3.2.6
  dio_cookie_manager: ^2.0.0

  common:
    path: ../common
  localization:
    path: ../localization # 国际化
  getx:
    path: ../getx # getX包
    
dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5
  flutter_lints: ^1.0.4